# Form implementation generated from reading ui file 'EditProfile.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QPixmap


class Ui_MainWindow_EditProfile(object):


    # method for profile screen
    def Profile(self):
        from Profile import Ui_MainWindow_Profile
        self.window2 = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_Profile()
        self.ui.setupUi(self.window2)
        self.window2.show()


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.EditProfilebg = QtWidgets.QLabel(self.centralwidget)
        self.EditProfilebg.setGeometry(QtCore.QRect(0, 0, 400, 768))
        # self.EditProfilebg.setStyleSheet("background-image: url(:/newPrefix/Images/Edit Profile.png);")
        self.EditProfilebg.setPixmap(QPixmap("./Images/Edit Profile.png"))
        self.EditProfilebg.setText("")
        self.EditProfilebg.setObjectName("EditProfilebg")
        self.bgframe = QtWidgets.QFrame(self.centralwidget)
        self.bgframe.setGeometry(QtCore.QRect(40, 78, 332, 211))
        self.bgframe.setStyleSheet("#bgframe{background-color: rgb(16, 106, 56);\n"
"border: 1px solid #707070;\n"
"border-radius: 14px;\n"
"opacity: \n"
"}")
        self.bgframe.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.bgframe.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.bgframe.setObjectName("bgframe")
        self.profilepic = QtWidgets.QLabel(self.bgframe)
        self.profilepic.setGeometry(QtCore.QRect(120, 20, 100, 104))
        self.profilepic.setPixmap(QPixmap("./Images/ProfileSnippetIcon.png"))
        # self.profilepic.setStyleSheet("image: url(:/newPrefix/Ellipse 33.png);")
        self.profilepic.setText("")
        self.profilepic.setObjectName("profilepic")
        self.uploadPicBtn = QtWidgets.QPushButton(self.bgframe)
        self.uploadPicBtn.setGeometry(QtCore.QRect(40, 150, 126, 32))
        self.uploadPicBtn.setStyleSheet("#uploadPicBtn{\n"
"border-radius: 5px;\n"
"box-shadow: 0px 3px 6px #000000;\n"
"border: 2px solid #39B54A;\n"
"opacity: 1;\n"
"font-family: Montserrat;\n"
"font-size: 14px;\n"
"font-weight: 600;\n"
"color: #00000;\n"
"background-color: rgb(40, 232, 144);\n"
"}\n"
"\n"
"QPushButton#RegisterpushButton:hover{\n"
"\n"
"color: #FFFFFF ;\n"
"background-color: #28E890;\n"
"\n"
"\n"
"}")
        self.uploadPicBtn.setObjectName("uploadPicBtn")
        self.capturePicBtn = QtWidgets.QPushButton(self.bgframe)
        self.capturePicBtn.setGeometry(QtCore.QRect(180, 150, 131, 32))
        self.capturePicBtn.setStyleSheet("#capturePicBtn{\n"
"border-radius: 5px;\n"
"box-shadow: 0px 3px 6px #000000;\n"
"border: 2px solid #39B54A;\n"
"opacity: 1;\n"
"font-family: Montserrat;\n"
"font-size: 14px;\n"
"font-weight: 600;\n"
"color: #00000;\n"
"background-color: rgb(40, 232, 144);\n"
"}\n"
"\n"
"QPushButton#RegisterpushButton:hover{\n"
"\n"
"color: #FFFFFF ;\n"
"background-color: #28E890;\n"
"\n"
"\n"
"}")
        self.capturePicBtn.setObjectName("capturePicBtn")
        self.FirstNameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.FirstNameLineEdit.setGeometry(QtCore.QRect(59, 329, 282, 41))
        self.FirstNameLineEdit.setStyleSheet("#FirstNameLineEdit{\n"
"border: 2px solid var(--unnamed-color-106a38);\n"
"box-shadow: 0px 3px 6px #00000066;\n"
"border: 2px solid #106A38;\n"
"border-radius: 6px;\n"
"opacity: 1;\n"
"font: 15px \"Montserrat\";\n"
"color: #39B54A;\n"
"text-align: left;\n"
"\n"
"}")
        self.FirstNameLineEdit.setObjectName("FirstNameLineEdit")
        self.LastNamelineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.LastNamelineEdit.setGeometry(QtCore.QRect(59, 393, 282, 41))
        self.LastNamelineEdit.setStyleSheet("#LastNamelineEdit{\n"
"\n"
"border: 2px solid var(--unnamed-color-106a38);\n"
"box-shadow: 0px 3px 6px #00000066;\n"
"border: 2px solid #106A38;\n"
"border-radius: 6px;\n"
"opacity: 1;\n"
"font: 15px \"Montserrat\";\n"
"color: #39B54A;\n"
"text-align: left;\n"
"\n"
"\n"
"}")
        self.LastNamelineEdit.setObjectName("LastNamelineEdit")
        self.EmaillineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.EmaillineEdit.setGeometry(QtCore.QRect(59, 457, 282, 41))
        self.EmaillineEdit.setStyleSheet("#EmaillineEdit{\n"
"\n"
"border: 2px solid var(--unnamed-color-106a38);\n"
"box-shadow: 0px 3px 6px #00000066;\n"
"border: 2px solid #106A38;\n"
"border-radius: 6px;\n"
"opacity: 1;\n"
"font: 15px \"Montserrat\";\n"
"color: #39B54A;\n"
"text-align: left;\n"
"\n"
"\n"
"\n"
"}")
        self.EmaillineEdit.setObjectName("EmaillineEdit")
        self.UserNamelineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.UserNamelineEdit.setGeometry(QtCore.QRect(59, 521, 282, 41))
        self.UserNamelineEdit.setStyleSheet("#UserNamelineEdit{\n"
"border: 2px solid var(--unnamed-color-106a38);\n"
"box-shadow: 0px 3px 6px #00000066;\n"
"border: 2px solid #106A38;\n"
"border-radius: 6px;\n"
"opacity: 1;\n"
"font: 15px \"Montserrat\";\n"
"color: #39B54A;\n"
"text-align: left;\n"
"\n"
"\n"
"\n"
"\n"
"}")
        self.UserNamelineEdit.setObjectName("UserNamelineEdit")
        self.PasswordlineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.PasswordlineEdit.setGeometry(QtCore.QRect(59, 585, 282, 41))
        self.PasswordlineEdit.setStyleSheet("#PasswordlineEdit{\n"
"border: 2px solid var(--unnamed-color-106a38);\n"
"box-shadow: 0px 3px 6px #00000066;\n"
"border: 2px solid #106A38;\n"
"border-radius: 6px;\n"
"opacity: 1;\n"
"font: 15px \"Montserrat\";\n"
"color: #39B54A;\n"
"text-align: left;\n"
"\n"
"\n"
"\n"
"\n"
"}")
        self.PasswordlineEdit.setObjectName("PasswordlineEdit")
        self.saveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.saveBtn.setGeometry(QtCore.QRect(74, 697, 115, 32))
        self.saveBtn.setStyleSheet("#saveBtn{\n"
"border-radius: 5px;\n"
"box-shadow: 0px 3px 6px #000000;\n"
"border: 2px solid #39B54A;\n"
"opacity: 1;\n"
"font-family: Montserrat;\n"
"font-size: 14px;\n"
"font-weight: 600;\n"
"color: #00000;\n"
"background-color: rgb(40, 232, 144);\n"
"}\n"
"\n"
"QPushButton#RegisterpushButton:hover{\n"
"\n"
"color: #FFFFFF ;\n"
"background-color: #28E890;\n"
"\n"
"\n"
"}")
        self.saveBtn.setObjectName("saveBtn")
        self.cancelBtn = QtWidgets.QPushButton(self.centralwidget)
        self.cancelBtn.setGeometry(QtCore.QRect(219, 697, 115, 32))
        self.cancelBtn.setStyleSheet("#cancelBtn{\n"
"border-radius: 5px;\n"
"box-shadow: 0px 3px 6px #000000;\n"
"border: 2px solid #39B54A;\n"
"opacity: 1;\n"
"font-family: Montserrat;\n"
"font-size: 14px;\n"
"font-weight: 600;\n"
"    color: rgb(255, 255, 255);\n"
"background-color: transparent;\n"
"}\n"
"\n"
"QPushButton#RegisterpushButton:hover{\n"
"\n"
"color: #FFFFFF ;\n"
"background-color: #28E890;\n"
"\n"
"\n"
"}")
        self.cancelBtn.setObjectName("cancelBtn")

        self.cancelBtn.clicked.connect(self.Profile)
        self.cancelBtn.clicked.connect(MainWindow.close)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.uploadPicBtn.setText(_translate("MainWindow", "Upload Picture"))
        self.capturePicBtn.setText(_translate("MainWindow", "Capture Picture"))
        self.FirstNameLineEdit.setText(_translate("MainWindow", "   First name"))
        self.LastNamelineEdit.setText(_translate("MainWindow", "   Second name"))
        self.EmaillineEdit.setText(_translate("MainWindow", "   E-mail"))
        self.UserNamelineEdit.setText(_translate("MainWindow", "   User name"))
        self.PasswordlineEdit.setText(_translate("MainWindow", "   Password"))
        self.saveBtn.setText(_translate("MainWindow", "save"))
        self.cancelBtn.setText(_translate("MainWindow", "cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_EditProfile()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
