# Form implementation generated from reading ui file 'Profile.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from datetime import date, datetime

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QSize
from PyQt6.QtGui import QPixmap, QIcon


class Ui_MainWindow_Profile(object):


    # method for opening menu screen
    def Menu(self):
        from Menu import Ui_MainWindow_Menu
        self.window2 = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_Menu()
        self.ui.setupUi(self.window2)
        self.window2.show()
        MainWindow.hide()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1023, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.profile = QtWidgets.QLabel(self.centralwidget)
        self.profile.setGeometry(QtCore.QRect(0, 0, 1024, 768))
        self.profile.setPixmap(QPixmap("./Images/Profile.png"))
        # self.profile.setStyleSheet("background-image: url(:/newPrefix/Profile.png);")
        self.profile.setText("")
        self.profile.setObjectName("profile")
        self.dasboardicon = QtWidgets.QLabel(self.centralwidget)
        self.dasboardicon.setGeometry(QtCore.QRect(17, 262, 54, 29))
        self.dasboardicon.setPixmap(QPixmap("./Images/Group 308.png"))
        # self.dasboardicon.setStyleSheet("image: url(:/newPrefix/Group 308.png);")
        self.dasboardicon.setText("")
        self.dasboardicon.setObjectName("dasboardicon")
        self.psltorduicon = QtWidgets.QLabel(self.centralwidget)
        self.psltorduicon.setGeometry(QtCore.QRect(17, 330, 56, 35))
        self.psltorduicon.setPixmap(QPixmap("./Images/Group 309.png"))
        # self.psltorduicon.setStyleSheet("image: url(:/newPrefix/Group 309.png);")
        self.psltorduicon.setText("")
        self.psltorduicon.setObjectName("psltorduicon")
        self.audiotoUrduicon = QtWidgets.QLabel(self.centralwidget)
        self.audiotoUrduicon.setGeometry(QtCore.QRect(10, 403, 68, 35))
        self.audiotoUrduicon.setPixmap(QPixmap("./Images/Group 310.png"))
        # self.audiotoUrduicon.setStyleSheet("image: url(:/newPrefix/Group 310.png);")
        self.audiotoUrduicon.setText("")
        self.audiotoUrduicon.setObjectName("audiotoUrduicon")
        self.profileicon = QtWidgets.QLabel(self.centralwidget)
        self.profileicon.setGeometry(QtCore.QRect(24, 477, 40, 32))
        self.profileicon.setPixmap(QPixmap("./Images/Group 311.png"))
        # self.profileicon.setStyleSheet("image: url(:/newPrefix/Group 311.png);")
        self.profileicon.setText("")
        self.profileicon.setObjectName("profileicon")
        self.day = QtWidgets.QLabel(self.centralwidget)
        self.day.setGeometry(QtCore.QRect(159, 37, 123, 19))
        self.day.setStyleSheet("#day{\n"
"font: 16px \"Montserrat\";\n"
"text-align: left;\n"
"letter-spacing: 0px;\n"
"color: #FFFFFF;\n"
"opacity: 1;\n"
"\n"
"}")
        self.day.setObjectName("day")
        today = date.today()
        d2 = today.strftime("%B %d, %Y")
        # print("d2 =", d2)
        self.day.setText(d2)
        print(d2)

        self.timelabel = QtWidgets.QLabel(self.centralwidget)
        self.timelabel.setGeometry(QtCore.QRect(159, 52, 115, 52))
        self.timelabel.setStyleSheet("#timelabel{\n"
"text-align: left;\n"
# "letter-spacing: NaNpx;\n"
"color: #FFFFFF;\n"
"opacity: 1;\n"
"font: 28px \"Montserrat\";\n"
"\n"
"\n"
"}")
        self.timelabel.setObjectName("timelabel")
        now = datetime.now()
        t = now.strftime("%H:%M")
        self.timelabel.setText(t)
        print(t)

        self.profilelabel = QtWidgets.QLabel(self.centralwidget)
        self.profilelabel.setGeometry(QtCore.QRect(160, 150, 98, 27))
        self.profilelabel.setStyleSheet("#profilelabel{\n"
"text-align: left;\n"
"font: 22px \"Montserrat\";\n"
"letter-spacing: 0px;\n"
"color: #FFFFFF;\n"
"opacity: 1;\n"
"\n"
"\n"
"\n"
"\n"
"}")
        self.profilelabel.setObjectName("profilelabel")
        self.NotiLabel = QtWidgets.QLabel(self.centralwidget)
        self.NotiLabel.setGeometry(QtCore.QRect(764, 27, 16, 20))
        self.NotiLabel.setPixmap(QPixmap("./Images/Icon ionic-ios-notifications-outline.png"))
        # self.NotiLabel.setStyleSheet("image: url(:/newPrefix/Icon ionic-ios-notifications-outline.png);")
        self.NotiLabel.setText("")
        self.NotiLabel.setObjectName("NotiLabel")
        self.MsgLabel = QtWidgets.QLabel(self.centralwidget)
        self.MsgLabel.setGeometry(QtCore.QRect(812, 27, 16, 20))
        self.MsgLabel.setPixmap(QPixmap("./Images/Icon feather-message-square.png"))
        # self.MsgLabel.setStyleSheet("image: url(:/newPrefix/Icon feather-message-square.png);")
        self.MsgLabel.setText("")
        self.MsgLabel.setObjectName("MsgLabel")
        self.UsernameLabel = QtWidgets.QLabel(self.centralwidget)
        self.UsernameLabel.setGeometry(QtCore.QRect(863, 30, 72, 14))
        self.UsernameLabel.setStyleSheet("#UsernameLabel{\n"
"font: 11px \"Montserrat\";\n"
"color: #FFFFFF;\n"
"opacity: 1;\n"
"\n"
"\n"
"\n"
"}")
        self.UsernameLabel.setObjectName("UsernameLabel")
        self.ProfilepushButton = QtWidgets.QPushButton(self.centralwidget)
        self.ProfilepushButton.setGeometry(QtCore.QRect(947, 15, 44, 44))
        self.ProfilepushButton.setStyleSheet("#ProfilepushButton{\n"
"    image: url(:/newPrefix/Path 206.png);\n"
"border: 1px solid #00A65A;\n"
"border-radius: 22px;\n"
"background-color: Transparent;\n"
"\n"
"\n"
"\n"
"\n"
"}")
        self.ProfilepushButton.setText("")
        self.ProfilepushButton.setObjectName("ProfilepushButton")
        self.ProfilepushButton.setIconSize(QSize(35, 35))
        self.ProfilepushButton.setIcon(QIcon("./Images/Path 206.png"))

        self.profileImgLabel = QtWidgets.QLabel(self.centralwidget)
        self.profileImgLabel.setGeometry(QtCore.QRect(451, 137, 203, 203))
        self.profileImgLabel.setPixmap(QPixmap("./Images/Ellipse 33.png"))
        # self.profileImgLabel.setStyleSheet("image: url(:/newPrefix/Ellipse 33.png);")
        self.profileImgLabel.setText("")
        self.profileImgLabel.setObjectName("profileImgLabel")
        self.personalDetailBtn = QtWidgets.QPushButton(self.centralwidget)
        self.personalDetailBtn.setGeometry(QtCore.QRect(159, 384, 389, 46))
        self.personalDetailBtn.setStyleSheet("#personalDetailBtn{\n"
"font: 20px \"Montserrat\";\n"
"color:rgb(16, 106, 56);\n"
"    background-color: rgb(40, 232, 144);\n"
"border-radius: 5px;\n"
"\n"
"opacity: 1;\n"
"}")
        self.personalDetailBtn.setObjectName("personalDetailBtn")
        self.profileSettingsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.profileSettingsBtn.setGeometry(QtCore.QRect(585, 384, 389, 46))
        self.profileSettingsBtn.setStyleSheet("#profileSettingsBtn{\n"
"font: 20px \"Montserrat\";\n"
"color:rgb(16, 106, 56);\n"
"    background-color: rgb(40, 232, 144);\n"
"border-radius: 5px;\n"
"\n"
"opacity: 1;\n"
"}")
        self.profileSettingsBtn.setObjectName("profileSettingsBtn")
        self.privacyPolicyBtn = QtWidgets.QPushButton(self.centralwidget)
        self.privacyPolicyBtn.setGeometry(QtCore.QRect(367, 467, 389, 46))
        self.privacyPolicyBtn.setStyleSheet("#privacyPolicyBtn{\n"
"font: 20px \"Montserrat\";\n"
"color:rgb(16, 106, 56);\n"
"    background-color: rgb(40, 232, 144);\n"
"border-radius: 5px;\n"
"\n"
"opacity: 1;\n"
"}")
        self.privacyPolicyBtn.setObjectName("privacyPolicyBtn")
        self.Sidebar = QtWidgets.QPushButton(self.centralwidget)
        self.Sidebar.setGeometry(QtCore.QRect(-10, -15, 96, 795))
        self.Sidebar.setStyleSheet("#Sidebar{\n"
"\n"
"border-radius: 2px;\n"
"background-color: rgb(0, 166, 90);\n"
"\n"
"\n"
"}")
        self.Sidebar.setText("")
        self.Sidebar.setObjectName("Sidebar")
        self.Sidebar.clicked.connect(self.Menu)
        #self.Sidebar.clicked.connect(MainWindow.close)

        self.LogoLabel = QtWidgets.QLabel(self.centralwidget)
        self.LogoLabel.setGeometry(QtCore.QRect(14, 41, 62, 47))
        self.LogoLabel.setText("")
        self.LogoLabel.setObjectName("LogoLabel")
        self.profile.raise_()
        self.day.raise_()
        self.timelabel.raise_()
        self.profilelabel.raise_()
        self.NotiLabel.raise_()
        self.MsgLabel.raise_()
        self.UsernameLabel.raise_()
        self.ProfilepushButton.raise_()
        self.profileImgLabel.raise_()
        self.personalDetailBtn.raise_()
        self.profileSettingsBtn.raise_()
        self.privacyPolicyBtn.raise_()
        self.Sidebar.raise_()
        self.audiotoUrduicon.raise_()
        self.dasboardicon.raise_()
        self.profileicon.raise_()
        self.psltorduicon.raise_()
        self.LogoLabel.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1023, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        # self.day.setText(_translate("MainWindow", "Thursday, 25.10 "))
        # self.timelabel.setText(_translate("MainWindow", "5:48 PM"))
        self.profilelabel.setText(_translate("MainWindow", "PROFILE"))
        self.UsernameLabel.setText(_translate("MainWindow", "USERNAME"))
        self.personalDetailBtn.setText(_translate("MainWindow", "PERSONAL DETAILS"))
        self.profileSettingsBtn.setText(_translate("MainWindow", "PROFILE SETTING"))
        self.privacyPolicyBtn.setText(_translate("MainWindow", "PRIVACY & POLICY"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_Profile()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
