# Form implementation generated from reading ui file 'Profile.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from datetime import date, datetime

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QSize
from PyQt6.QtGui import QPixmap, QIcon


class Ui_MainWindow_Profile(object):



    # method for opening menu screen
    def Menu(self):
        from Menu import Ui_MainWindow_Menu
        self.window2 = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_Menu()
        self.ui.setupUi(self.window2)
        self.window2.show()

    # method for opening edit profile screen
    def EditProfile(self):
        from EditProfile import Ui_MainWindow_EditProfile
        self.window2 = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_EditProfile()
        self.ui.setupUi(self.window2)
        self.window2.show()


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1024, 768))
#         self.label.setStyleSheet("\n"
# "background-image: url(:/newPrefix/Images/Profile.png);")
        self.label.setPixmap(QPixmap("./Images/Profile.png"))
        self.label.setText("")
        self.label.setObjectName("label")
        self.SideBarBtn = QtWidgets.QPushButton(self.centralwidget)
        self.SideBarBtn.setGeometry(QtCore.QRect(-10, -15, 96, 785))
        self.SideBarBtn.setStyleSheet("#SideBarBtn{\n"
"\n"
"border-radius: 2px;\n"
"background-color: rgb(0, 166, 90);\n"
"\n"
"\n"
"}")
        self.SideBarBtn.setText("")

        self.SideBarBtn.setIcon(QIcon("./Images/Side Bar.jpg"))
        self.SideBarBtn.setObjectName("SideBarBtn")
        self.SideBarBtn.clicked.connect(self.Menu)
        self.SideBarBtn.clicked.connect(MainWindow.close)

        self.dasboardicon = QtWidgets.QLabel(self.centralwidget)
        self.dasboardicon.setGeometry(QtCore.QRect(17, 262, 54, 29))
        # self.dasboardicon.setStyleSheet("background-image: url(:/newPrefix/Group 308.png);")
        self.dasboardicon.setPixmap(QPixmap("./Images/Group 308.png"))
        self.dasboardicon.setText("")
        self.dasboardicon.setObjectName("dasboardicon")
        self.psltorduicon = QtWidgets.QLabel(self.centralwidget)
        self.psltorduicon.setGeometry(QtCore.QRect(17, 330, 56, 35))
        # self.psltorduicon.setStyleSheet("background-image: url(:/newPrefix/Group 309.png);")
        self.psltorduicon.setPixmap(QPixmap("./Images/Group 309.png"))
        self.psltorduicon.setText("")
        self.psltorduicon.setObjectName("psltorduicon")
        self.audiotoUrduicon = QtWidgets.QLabel(self.centralwidget)
        self.audiotoUrduicon.setGeometry(QtCore.QRect(10, 403, 68, 35))
        # self.audiotoUrduicon.setStyleSheet("background-image: url(:/newPrefix/Group 310.png);")
        self.audiotoUrduicon.setPixmap(QPixmap("./Images/Group 310.png"))
        self.audiotoUrduicon.setText("")
        self.audiotoUrduicon.setObjectName("audiotoUrduicon")
        self.profileicon = QtWidgets.QLabel(self.centralwidget)
        self.profileicon.setGeometry(QtCore.QRect(24, 477, 40, 32))
        # self.profileicon.setStyleSheet("background-image: url(:/newPrefix/Group 311.png);")
        self.profileicon.setPixmap(QPixmap("./Images/Group 311.png"))
        self.profileicon.setText("")
        self.profileicon.setObjectName("profileicon")
        self.LogoLabel = QtWidgets.QLabel(self.centralwidget)
        self.LogoLabel.setGeometry(QtCore.QRect(14, 47, 51, 41))
        # self.LogoLabel.setStyleSheet("background-image: url(:/newPrefix/Images/check.png);")
        self.LogoLabel.setPixmap(QPixmap("./Images/check.png"))
        self.LogoLabel.setText("")
        self.LogoLabel.setObjectName("LogoLabel")
        self.day = QtWidgets.QLabel(self.centralwidget)
        self.day.setGeometry(QtCore.QRect(159, 37, 153, 19))
        self.day.setStyleSheet("#day{\n"
"font: 16px \"Montserrat\";\n"
"text-align: left;\n"
# "letter-spacing: 0px;\n"
"color: #FFFFFF;\n"
"opacity: 1;\n"
"\n"
"}")
        self.day.setObjectName("day")
        today = date.today()
        d2 = today.strftime("%B %d, %Y")
        # print("d2 =", d2)
        self.day.setText(d2)


        self.timelabel = QtWidgets.QLabel(self.centralwidget)
        self.timelabel.setGeometry(QtCore.QRect(159, 52, 115, 52))
        self.timelabel.setStyleSheet("#timelabel{\n"
"text-align: left;\n"
# "letter-spacing: NaNpx;\n"
"color: #FFFFFF;\n"
"opacity: 1;\n"
"font: 28px \"Montserrat\";\n"
"\n"
"\n"
"}")
        self.timelabel.setObjectName("timelabel")

        now = datetime.now()
        t = now.strftime("%H:%M")
        self.timelabel.setText(t)

        self.profilelabel = QtWidgets.QLabel(self.centralwidget)
        self.profilelabel.setGeometry(QtCore.QRect(160, 135, 98, 27))
        self.profilelabel.setStyleSheet("#profilelabel{\n"
"text-align: left;\n"
"font: 22px \"Montserrat\";\n"
"letter-spacing: 0px;\n"
"color: #FFFFFF;\n"
"opacity: 1;\n"
"\n"
"\n"
"\n"
"\n"
"}")
        self.profilelabel.setObjectName("profilelabel")
        self.NotiLabel = QtWidgets.QLabel(self.centralwidget)
        self.NotiLabel.setGeometry(QtCore.QRect(764, 27, 16, 20))
#         self.NotiLabel.setStyleSheet("\n"
# "background-image: url(:/newPrefix/Icon ionic-ios-notifications-outline.png);")
        self.NotiLabel.setText("")
        self.NotiLabel.setObjectName("NotiLabel")
        self.NotiLabel.setPixmap(QPixmap("./Images/Icon ionic-ios-notifications-outline.png"))

        self.MsgLabel = QtWidgets.QLabel(self.centralwidget)
        self.MsgLabel.setGeometry(QtCore.QRect(812, 27, 16, 16))
        # self.MsgLabel.setStyleSheet("background-image: url(:/newPrefix/Icon feather-message-square.png);")
        self.MsgLabel.setPixmap(QPixmap("./Images/Icon feather-message-square.png"))
        self.MsgLabel.setText("")
        self.MsgLabel.setObjectName("MsgLabel")
        self.UsernameLabel = QtWidgets.QLabel(self.centralwidget)
        self.UsernameLabel.setGeometry(QtCore.QRect(863, 30, 72, 14))
        self.UsernameLabel.setStyleSheet("#UsernameLabel{\n"
"font: 11px \"Montserrat\";\n"
"color: #FFFFFF;\n"
"opacity: 1;\n"
"\n"
"\n"
"\n"
"}")
        self.UsernameLabel.setObjectName("UsernameLabel")
        self.ProfilepushButton = QtWidgets.QPushButton(self.centralwidget)
        self.ProfilepushButton.setGeometry(QtCore.QRect(947, 15, 44, 44))
        self.ProfilepushButton.setStyleSheet("#ProfilepushButton{\n"
"\n"
"    background-image: url(:/newPrefix/Path 206.png);\n"
"border: 1px solid #00A65A;\n"
"border-radius: 22px;\n"
"background-color: Transparent;\n"
"\n"
"\n"
"\n"
"\n"
"}")
        self.ProfilepushButton.setText("")
        self.ProfilepushButton.setObjectName("ProfilepushButton")
        self.ProfilepushButton.setIconSize(QSize(35, 35))
        self.ProfilepushButton.setIcon(QIcon("./Images/Path 206.png"))

        self.ProfBoxPicpushBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ProfBoxPicpushBtn.setGeometry(QtCore.QRect(466, 200, 156, 160))
        self.ProfBoxPicpushBtn.setStyleSheet("#ProfBoxPicpushBtn{\n"
"image: url(:/newPrefix/Ellipse 33.png);\n"
"\n"
"border-radius: 100px;\n"
"background-color: Transparent;\n"
"\n"
"\n"
"\n"
"\n"
"}")
        self.ProfBoxPicpushBtn.setText("")
        self.ProfBoxPicpushBtn.setObjectName("ProfBoxPicpushBtn")


        self.usernameLabel = QtWidgets.QLabel(self.centralwidget)
        self.usernameLabel.setGeometry(QtCore.QRect(453, 399, 183, 24))
        self.usernameLabel.setStyleSheet("#usernameLabel{\n"
"color: rgb(0, 0, 0);\n"
"text-align: center;\n"
"font: 20px Montserrat;\n"
"font-weight:600;\n"
"letter-spacing: 0px;\n"
"opacity: 1;\n"
"}")
        self.usernameLabel.setText("USERNAME")
        self.usernameLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.usernameLabel.setObjectName("usernameLabel")
        self.linelabel = QtWidgets.QLabel(self.centralwidget)
        self.linelabel.setGeometry(QtCore.QRect(362, 500, 364, 16))
        self.linelabel.setStyleSheet("image: url(:/newPrefix/Images/profile5.png);\n"
"")
        self.linelabel.setText("")
        self.linelabel.setObjectName("linelabel")
        self.howToUseBtn = QtWidgets.QPushButton(self.centralwidget)
        self.howToUseBtn.setGeometry(QtCore.QRect(369, 544, 79, 79))
        self.howToUseBtn.setStyleSheet("#howToUseBtn{\n"
"border-radius: 39px;\n"
"background-color: #00A65A;\n"
"opacity: 1;\n"
"    image: url(:/newPrefix/noun_Curious_3194465.png);\n"
"}")
        self.howToUseBtn.setText("")
        self.howToUseBtn.setObjectName("howToUseBtn")
        self.privacyPolBtn = QtWidgets.QPushButton(self.centralwidget)
        self.privacyPolBtn.setGeometry(QtCore.QRect(502, 542, 79, 79))
        self.privacyPolBtn.setStyleSheet("#privacyPolBtn{\n"
"border-radius: 39px;\n"
"background-color: #00A65A;\n"
"opacity: 1;\n"
"    image: url(:/newPrefix/noun_privacy policy_3908089.png);\n"
"}")
        self.privacyPolBtn.setText("")
        self.privacyPolBtn.setObjectName("privacyPolBtn")
        self.editProfileBtn = QtWidgets.QPushButton(self.centralwidget)
        self.editProfileBtn.setGeometry(QtCore.QRect(635, 542, 79, 79))
        self.editProfileBtn.setStyleSheet("#editProfileBtn{\n"
"    image: url(:/newPrefix/noun_Edit Profile_934563.png);\n"
"border-radius: 39px;\n"
"background-color: #00A65A;\n"
"opacity: 1;\n"
"\n"
"}")
        self.editProfileBtn.setText("")
        self.editProfileBtn.setObjectName("editProfileBtn")
        self.editProfileBtn.clicked.connect(self.EditProfile)
        self.editProfileBtn.clicked.connect(MainWindow.close)

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(328, 198, 431, 533))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setEnabled(True)
        self.plainTextEdit.setGeometry(QtCore.QRect(424, 430, 239, 51))
        self.plainTextEdit.setStyleSheet("#plainTextEdit{\n"
"font: 14px Montserrat;\n"
"letter-spacing: 0px;\n"
"color: #000000;\n"
"opacity: 1;\n"
"border:none;\n"
"\n"
"}")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.HowtoUseLabel = QtWidgets.QLabel(self.centralwidget)
        self.HowtoUseLabel.setGeometry(QtCore.QRect(361, 636, 101, 19))
        self.HowtoUseLabel.setStyleSheet("#HowtoUseLabel{\n"
"color: rgb(0, 0, 0);\n"
"font: 16px \"Montserrat\";\n"
"font-weight:600;\n"
"\n"
"\n"
"\n"
"}")
        self.HowtoUseLabel.setObjectName("HowtoUseLabel")
        self.howToUseBtn.setIconSize(QSize(35, 35))
        self.howToUseBtn.setIcon(QIcon("./Images/noun_Curious_3194465.png"))

        self.PrivacyPolicyLabel = QtWidgets.QLabel(self.centralwidget)
        self.PrivacyPolicyLabel.setGeometry(QtCore.QRect(480, 636, 141, 19))
        self.PrivacyPolicyLabel.setStyleSheet("#PrivacyPolicyLabel{\n"
"color: rgb(0, 0, 0);\n"
"font: 16px \"Montserrat\";\n"
"font-weight:600;\n"
"\n"
"\n"
"\n"
"}")
        self.PrivacyPolicyLabel.setObjectName("PrivacyPolicyLabel")
        self.privacyPolBtn.setIconSize(QSize(35, 35))
        self.privacyPolBtn.setIcon(QIcon("./Images/noun_privacy policy_3908089.png"))


        self.EditProfileLabel = QtWidgets.QLabel(self.centralwidget)
        self.EditProfileLabel.setGeometry(QtCore.QRect(631, 636, 98, 19))
        self.EditProfileLabel.setStyleSheet("#EditProfileLabel{\n"
"color: rgb(0, 0, 0);\n"
"font: 16px \"Montserrat\";\n"
"font-weight:600;\n"
                                            "border-radius: 88px;\n"
"\n"
"\n"
"\n"
"}")
        self.EditProfileLabel.setObjectName("EditProfileLabel")
        self.editProfileBtn.setIconSize(QSize(35, 35))
        self.editProfileBtn.setIcon(QIcon("./Images/noun_Edit Profile_934563.png"))


        self.ProfileLabel = QtWidgets.QLabel(self.centralwidget)
        self.ProfileLabel.setGeometry(QtCore.QRect(466, 224, 156, 160))
        # self.ProfileLabel.setStyleSheet("image: url(:/newPrefix/ProfileSnippetIcon.png);")
        self.ProfileLabel.setPixmap(QPixmap("./Images/Ellipse 33.png"))

        self.ProfileLabel.setText("")
        self.ProfileLabel.setObjectName("ProfileLabel")
        self.label.raise_()
        self.SideBarBtn.raise_()
        self.dasboardicon.raise_()
        self.psltorduicon.raise_()
        self.audiotoUrduicon.raise_()
        self.profileicon.raise_()
        self.LogoLabel.raise_()
        self.day.raise_()
        self.timelabel.raise_()
        self.profilelabel.raise_()
        self.NotiLabel.raise_()
        self.MsgLabel.raise_()
        self.UsernameLabel.raise_()
        self.ProfilepushButton.raise_()
        self.ProfBoxPicpushBtn.raise_()
        self.label_2.raise_()
        self.linelabel.raise_()
        self.usernameLabel.raise_()
        self.privacyPolBtn.raise_()
        self.howToUseBtn.raise_()
        self.editProfileBtn.raise_()
        self.plainTextEdit.raise_()
        self.HowtoUseLabel.raise_()
        self.PrivacyPolicyLabel.raise_()
        self.EditProfileLabel.raise_()
        self.ProfileLabel.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        # self.day.setText(_translate("MainWindow", "Thursday, 25.10 "))
        # self.timelabel.setText(_translate("MainWindow", "5:48 PM"))
        self.profilelabel.setText(_translate("MainWindow", "PROFILE"))
        self.UsernameLabel.setText(_translate("MainWindow", "USERNAME"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "But I must explain to you how all this mistaken  explain to you"))
        self.HowtoUseLabel.setText(_translate("MainWindow", "How To Use"))
        self.PrivacyPolicyLabel.setText(_translate("MainWindow", "Privacy & Policy"))
        self.EditProfileLabel.setText(_translate("MainWindow", "Edit Profile"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_Profile()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
